angular.module('sfmuniApp', 
['ngRoute',
 'appRoutes',
 'sfmuniAppCtrl',
 'NextBusService',
 'HomeCtrl',
 'MapCtrl',
 'BusMap',
 'MapPageCtrl',
 'BusServiceFactoryModule',
 'MapServiceFactoryModule',
 'CitiesServiceFactoryModule',
 'LocalMapServiceModule'
 ]);